### ISSUE TITLE
Solidity syntax highlighting

### ISSUE THREAD

**Issue by arthurk** [bartTC/dpaste#105]
Hey Martin, hope you're doing well!

Would it be possible to add the Solidity lexer from https://pypi.python.org/pypi/pygments-lexer-solidity in the next release of dpaste.de? 

Right now there's no good paste-service which offers this. Most devs share snippets via pastebin, which are hard to read.  I think a lot of people would appreciate it!

**Comment by bartTC** [comment]
Sure thing! https://dpaste.de/bZFU

It's in the `v3` branch now and its live on dpaste.de. The actual release will take a bit as I want to implement #69 too.
