### ISSUE TITLE
dpaste.de: http > https redirect isn't functional

### ISSUE THREAD

**Issue by pythdasch** [bartTC/dpaste#106]
I think you forgot to put a csrf_token in your form :)

when submitting => csrf_failed

**Comment by alex-petr** [comment]
@bartTC 
### Got error that prevent to send code snippets

Hi :) Very like your simple but powerful service, and using it with pleasure for a long time.
But some time ago I got error, after any code submitting:

> Forbidden (403)
> CSRF verification failed. Request aborted.
> 
> You are seeing this message because this site requires a CSRF cookie when submitting forms. This cookie is required for security reasons, to ensure that your browser is not being hijacked by third parties.
> 
> If you have configured your browser to disable cookies, please re-enable them, at least for this site, or for 'same-origin' requests.
> 
> More information is available with DEBUG=True.


Tried to clear cache, open in incognito window -- same result :(
Can you fix it and advise me how to use your service or maybe what cause this error?

**Comment by bartTC** [comment]
Whats the URl you folks use? I don't get such an error, I dont see anything in the logs regarding CSRF.

**Comment by alex-petr** [comment]
http://prntscr.com/j7tsqq
http://prntscr.com/j7tt08

**Comment by alex-petr** [comment]
@bartTC Maybe problem in some `CSRF cookie` as mentioned in error message?

**Comment by bartTC** [comment]
OK, looks like you guys use `http://dpaste.de` (no SSL). The http > https redirect does not seem to work correctly, you are stuck on http, but the CSRF cookie is set to 'secure', so it requires SSL. It doesn't kick in for that reason.

Workaround for now is to go to `https://dpaste.de/` once, it should all work fine there.

**Comment by bartTC** [comment]
This is fixed.

```
❯ curl -I http://dpaste.de/
HTTP/1.1 301 Moved Permanently
Server: nginx/1.14.0
Date: Fri, 20 Apr 2018 15:25:43 GMT
Content-Type: text/html
Content-Length: 185
Connection: keep-alive
Location: https://dpaste.de/
Strict-Transport-Security: max-age=15768000; includeSubDomains
```
