### ISSUE TITLE
Not able to specify a lexer

### ISSUE THREAD

**Issue by xdb64** [bartTC/dpaste#111]
If I try to specify a lexer when sending the request, I get:

```
Traceback (most recent call last):
  File "application.py", line 30, in <module>
  File "requests/models.py", line 939, in raise_for_status
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://dpaste.de/api/
[29409] Failed to execute script application

```

Also, it seems that the [list of available lexers](https://github.com/bartTC/dpaste/blob/master/dpaste/highlight.py#L25) from the [official API page](https://dpaste.readthedocs.io/en/latest/api.html) is gone.

**Comment by bartTC** [comment]
@adder46 I don't see what you're doing or how you call the API with your traceback above. It's a traceback of your application, I can only see dpaste returns a HTTP 400 Bad Request.

The documention you linked is deprecated, you find the latest docs on https://docs.elephant.house/dpaste/api.html.

**Comment by adder46** [comment]
@bartTC This is the [source code](https://github.com/adder46/dpastebin/blob/master/application.py) in question, and I'm trying to do something like:

`cat spam.sh | dpaste --lexer bash`

**Comment by adder46** [comment]
Hmm, alright. Just one more thing -- I'm not quite sure why does it work when I pass no `lexer` value (pass it `None`)? Does passing `None` assume that `lexer` value (`arguments["LANGUAGE"]`) is `python`? Thanks.

**Comment by bartTC** [comment]
What means it 'doesn't work'? Whats the response body content? If you pass an invalid lexer name it should tell you that, and give you a list of options.

**Comment by adder46** [comment]
It seems that we don't understand each other. 
I'm just saying that it is possible to pass only the `expires` (note that `arguments["LANGUAGE"]` is `None` here):
```
$ cat ~/.bashrc | dpaste --expires onetime
<Response [200]>
https://dpaste.de/sPaM
```
...whereas it's not possible to only pass `lexer`.
```
$ cat ~/.bashrc | dpaste --lexer bash
<Response [400]>
Invalid expire choice "bash" given. Valid values are: 3600, 86400, onetime, 604800
``` 
It seems that if you want to specify the lexer, you must pass both `expires` and `lexer`:

```
$ cat ~/.bashrc | dpaste --expires onetime --lexer bash
<Response [200]>
https://dpaste.de/eggS
```
If only `expires` had a default value, like `lexer` has.
