### ISSUE TITLE
IPython extension using dpaste

### ISSUE THREAD

**Issue by HerveMignot** [bartTC/dpaste#115]
Hello, I have written an IPython extension using dpaste.de API to easily share code between people working on notebooks.
You can find additional details here: https://pypi.org/project/dpaste-magic/
Thank you for developping and maintaining dpaste!

Hervé

**Comment by bartTC** [comment]
Thank you, I added it to the list https://docs.elephant.house/dpaste/api.html#third-party-api-integration-into-editors
