### ISSUE TITLE
Suggestion for the default option for text being entered

### ISSUE THREAD

**Issue by Zero3K** [bartTC/dpaste#116]
I think that it should be Plain Text instead of Python.

**Comment by bartTC** [comment]
If this is for your own installation, then there is a config to set the defualt lexer: https://github.com/bartTC/dpaste/blob/master/dpaste/apps.py#L19-L21

If this is regarding dpaste.de then I think python is fine. The vast majority of snippets are code based, and of them Python is the most frequent one.
