### ISSUE TITLE
Raw view is gone

### ISSUE THREAD

**Issue by Kiwi** [bartTC/dpaste#120]
I really like dpaste.de but now that raw view isn't an option it's not nearly as useful :(

I can't tell if it was intentionally disabled or if it (which it looks like may have happened) was just disabled as part of an update? Anyway, if it's not a problem to have it on that'd be great!

Thanks for the service!

**Comment by bartTC** [comment]
Disabling Raw view is a feature I added in 3.1, https://github.com/bartTC/dpaste/blob/master/CHANGELOG.rst

It was necessary because dpaste.de's raw view mode was used to send commands to bots. May I ask what specific reason you need the raw view for? Maybe we can find an alternative.

**Comment by mathieu-aubin** [comment]
Myself, the raw view is very important for quickly sharing code (mostly bash scripts) with my entourage

I guess that it's also being used the same way to send stuff to bots but as always, the good people pay for the bad ones

**Comment by Kiwi** [comment]
Yeah, that basically. and I thought it might be because of abuse. sigh. I can't easily download/copy paste code (or whatever, often it's logs or several files) snippets if it has the html. The indentation is getting messed up in that mode, too. Raw just works (tm). Support channels don't like paste sites without a raw mode. (in addition to other things that I'm glad dpaste.de has so far avoided, like third party js and tons of ads, etc. that are frowned upon) I also usually share the raw version on IRC to make it slightly more effort for someone to delete it before people see it... :) I've just been using gists a lot more (for this and other reasons too) but my paste client works with dpaste.de and not gists... yet. I'm rewriting it. >.>

Apropos of nothing it seems kind of weird they're using dpaste.de I'd think the 7 day limit would be problematic to their interests and there are tons of other sites but what do I know heh. script kiddies gonna script, I guess. I'm not sure what kind of compromise there could be in light of that. *shrug* :(

**Comment by bartTC** [comment]
Thanks for the feedback, I think I have a solution for this that satisfies everyone. 

>  I'd think the 7 day limit would be problematic to their interests and there are tons of other sites but what do I know 

Exactly. I already limited the max lifetime from 30 days to 7 for this purpose, I thought this would make it unattractive enough.

**Comment by bartTC** [comment]
I brought the 'raw' mode back to dpaste: https://dpaste.de/1fJx/raw

If you look closely you will see that the page content is actual HTML, not plain text. But visually its identical and 'select all and copy to clipboard' should work just as fine. 

For my reason its only important that its not plain text so the 'script' can not loaded directly onto a machine and executed. 

There's also a dedicated 'copy snippet (to clipboard)' button now.
