### ISSUE TITLE
Mobile experience is terrible

### ISSUE THREAD

**Issue by bartTC** [bartTC/dpaste#122]
The mobile experience of dpaste.de is terrible at the moment. We should be at least give a basic form and good viewing experience for snippets. 

![MjekuQ](https://user-images.githubusercontent.com/1896/59431419-32c04780-8de5-11e9-9408-a37ba5bb54c9.png)
![dfCyKq](https://user-images.githubusercontent.com/1896/59431420-32c04780-8de5-11e9-979d-24ae3fa506c0.png)

**Comment by mathieu-aubin** [comment]
ouch

**Comment by bartTC** [comment]
This is fixed. ❤️ CSS Grid.

![](https://d.pr/i/BhiNQV.png)
![](https://d.pr/i/4CZvOl.png)
