### ISSUE TITLE
Make the term 'dpaste' editable by config

### ISSUE THREAD

**Issue by bartTC** [bartTC/dpaste#123]
There are a couple of static 'dpaste' strings in the templates, e.g. in the title or add-snippet header. Ideally that term is editable by the app config so users can give their dpaste installation a more fancy name. With emojis.

**Comment by Rodrigo-NH** [comment]
Hi bartTC. We thought the same thing while setting up dpaste for http://bsd.to (me and koobs). I ended by just changing it directly in the template (also for favicon.ico). Trying to understand how to manage this I ended with https://github.com/Rodrigo-NH/dpaste/commit/b7a5fd1ee1ff7a7b94a0027b24f302571dc7cb18 but not sure if it's the best (or good enough) approach for the task. Thanks for dpaste!

**Comment by bartTC** [comment]
Fixed in 34b970cf5d3b07ecbe90d97bc068d3206441978d. 

You can add arbitrary HTML too now, please see the AppConfig.
