### ISSUE TITLE
Document static file compilation for app installation

### ISSUE THREAD

**Issue by Nekmo** [bartTC/dpaste#125]
The package can not be used, static files are missing.

**Comment by bartTC** [comment]
Those are not in the repository since they are generated 'on demand'. Having them compiled in the repo would lead to endless merge conflicts.

`npm install` should do everything for you.

This part is missing in the docs.

**Comment by Nekmo** [comment]
So it does not make sense to create a Pypi package.

The Pypi package can be deleted if it is necessary to clone the project and install npm to use Dpaste.

```
FROM nikolaik/python-nodejs:python3.7-nodejs12

ENV PYTHONUNBUFFERED 1

RUN apt-get update
RUN apt-get install gettext -y
WORKDIR /tmp
COPY requirements.txt .
RUN echo "Installing requirements"
RUN pip install -r requirements.txt
RUN mkdir -p /var/log/gunicorn
RUN git clone https://github.com/bartTC/dpaste.git dpaste
WORKDIR /tmp/dpaste
RUN npm install
RUN npm run postinstall
RUN mkdir -p /usr/local/lib/python3.7/site-packages/dpaste/static
RUN cp build/* /usr/local/lib/python3.7/site-packages/dpaste/static/
WORKDIR /code
ENV PYTHONPATH "/code:${PYTHONPATH}"
ENTRYPOINT ["gunicorn", "-w", "4", "-b", "0.0.0.0:8000", "paste.wsgi:application"]
```

This is the dockerfile to be able to use this project, in case anyone needs it.

**Comment by bartTC** [comment]
I think you're right. I'll see how to ship the compiled static assets with the pypi package.

**Comment by Nekmo** [comment]
You can compile and deploy to Pypi using Travis.

https://docs.travis-ci.com/user/deployment/pypi/

**Comment by bartTC** [comment]
v3.3 now ships with compiled static files. Thank your for the insight. https://pypi.org/project/dpaste/
