### ISSUE TITLE
Highlighted full page view ?

### ISSUE THREAD

**Issue by spapas** [bartTC/dpaste#126]
Is it possible to add a highlighted full page view? Something like `/raw` but with the code highlighted. This would be useful to included each snippet in other sites using an `iframe` (i.e in web irc clients). 

If you want i'd be happy to provide a PR for this functionality.

**Comment by spapas** [comment]
Also please notice that for this to actually have any value you'll need to configure the new view to allow it to be included in an iframe using `@xframe_options_exempt`: https://docs.djangoproject.com/en/2.2/ref/clickjacking/#setting-x-frame-options-for-all-responses

**Comment by bartTC** [comment]
I recently added the ability to have the raw view rendered with HTML, so adding above feature would be pretty easy by overriding or adding a template there. 

I myself am pretty reluctant to this idea of an iframe. I could see having a dedicated API view that returns the rendered snippet, which you call and display how you need it. E.g. only the first three code lines as a preview in your IRC example.

**Comment by spapas** [comment]
Hello @bartTC yes I read the discussion about the raw view and I agree that it is rather easy feature to implement.

Also, a dedicated API as you propose would be even better (of course it would still need to allow cross origin requests to be useful) than including the html view in an iframe! 

I just mentioned using a simple html view and embedding it in an iframe because this is rather common in similar situations. For example take a look at how the glowing bear IRC client includes pastebins: https://github.com/glowing-bear/glowing-bear/blob/master/js/plugins.js#L475 (it also uses iframes for various other services).

**Comment by bartTC** [comment]
This is in. It's called Slim mode. 

![](https://d.pr/i/9tiP0g.png)
