### ISSUE TITLE
Anyone can delete a paste

### ISSUE THREAD

**Issue by supakeen** [bartTC/dpaste#130]
Hi, when I visit a paste made by someone that they've linked in an IRC channel or such I have to option to delete that paste. Is that intentional? It often ends up with someone clicking that link and removing the paste.

**Comment by bartTC** [comment]
This is intentional to make it pointless for spam and easy for other uses to erase sensitive informatin as quickly as possible.

**Comment by bartTC** [comment]
> It often ends up with someone clicking that link and removing the paste.

I do not believe this, or they do it intentional too. dpaste is meant to share code and other possibly sensitive information. If people think it should be deleted then there's probably a reason for it.
