### ISSUE TITLE
Word warp doesn't work on plain text

### ISSUE THREAD

**Issue by LunarTwilight** [bartTC/dpaste#132]
If you create a paste that has a very long line (to the point where it goes off screen and you get a scrollbar) and set the options to expire in one hour (I don't think this has any effect, but its what I tested with) and the type to plain text, then the word wrap checkbox doesn't do anything, and theres no error in the console.

**Comment by bartTC** [comment]
Could you post an example? Is this about a very long text or just one ridicolous long word? 

The wrap checkbox does indeed not work in plain text mode, its enabled by default.

**Comment by LunarTwilight** [comment]
It was some regex (that I'm not gonna share because it was for a profanity blacklist), but I managed to recreate it with some text by removing all the spaces, see https://dpaste.de/JAGO

**Comment by bartTC** [comment]
I think thats what to expect. Its not ideal but I dont see a proper solution for this. I can't arbitrarily add linebreaks into those words otherwise you couldn't copy/paste it anymore.

**Comment by bartTC** [comment]
Re-opened because I figured that theres a CSS property `word-wrap: anywhere;` which does what it says. It would work in these situations. Will look into it.

**Comment by LunarTwilight** [comment]
> Re-opened

The issue still says its closed for me?

**Comment by bartTC** [comment]
This is fixed.
