### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by jaypatelani** [bartTC/dpaste#134]
Maybe if possible add "nc" to get terminal text to BSD.to termbin.com uses this port  : https://github.com/solusipse/fiche/blob/master/README.md

**Comment by bartTC** [comment]
If I understand correctly 'fiche' needs a dedicated API endpoint on dpaste where it accepts fiche code, right? Happy to accpet a Pull request here, I am personally not interested in this.

There's a multitude of alternatives and you can easily add yourself an alias that does the same as fiche, for dpaste. Its documented here https://dpaste.readthedocs.io/en/latest/api.html#third-party-api-integration-into-editors
