### ISSUE TITLE
Django 3 compatibility: staticfiles was removed

### ISSUE THREAD

**Issue by rain0r** [bartTC/dpaste#135]
The file `templates/dpaste/base.html` uses `{% load staticfiles %}` which was [removed](https://docs.djangoproject.com/en/3.0/releases/3.0/#features-removed-in-3-0) in Django 3.

Thus, this package does not work with Django 3.

**Comment by bartTC** [comment]
django-csp is currently not 3.0 ready either https://github.com/mozilla/django-csp/issues/129

**Comment by bartTC** [comment]
Fixed in 63a8500cc82202c80d4d17e7f2bed027454a4a4b. django-csp will be a separate issue.
