### ISSUE TITLE
static inline makes it difficult to use cloudfront storage 

### ISSUE THREAD

**Issue by jamesbeedy** [bartTC/dpaste#138]
## Description
I would like to deploy dpaste as a serverless application that uses cloudfront to serve the assets.

The use of static inline and the 
`from django.contrib.staticfiles.storage import staticfiles_storage` import make using cloudfront near impossible.

## Acceptance Criteria
Remove static inline for generic django staticfiles functionality.

Deploy dpaste using cloudfront as a cdn and see that the assets load.

**Comment by jamesbeedy** [comment]
Example of a fully serverless version of dpaste, including serverless database -> https://github.com/peopledatalabs/pdl-dpaste/blob/master/serverless.yaml

**Comment by bartTC** [comment]
Could you elaborate more what you mean with Serverless? There still needs to be a server that runs the Python code and serves it classically with a webserver. 

The idea of staticinline is that you *don't* have any assets to serve, everything is inline with one document for performance reasons. 

I don't think this is an issue with dpaste, but also django-staticinline should work fine with external storages. I assume you use Boto to connect to S3. Could you leave an issue here https://github.com/bartTC/django-staticinline/issues with your rough AWS setup and staticfile related settings so I can replicate it?

Your yaml Link does not appear to work, it returns a Not found for me.

**Comment by jamesbeedy** [comment]
Could you try the link again, I think the repo should be private now. Yes I can elaborate further and move this over to the other repo. Thanks!
