### ISSUE TITLE
More expire time options

### ISSUE THREAD

**Issue by jaggzh** [bartTC/dpaste#144]
## Description
Thanks for all the years of pasteall!
I think, for sharing with people online, more short-term expire options should be available, like definitely "one day" is good for some sharing in chats.
I'd have: 1h, 2h, 12h, 1 day, and then the rest...

**Comment by bartTC** [comment]
There is already 1h and 1day. I dont think 2h or 12h add much benefit. 

You can customize this in your own dpaste installation. https://dpaste.readthedocs.io/en/latest/settings.html
