### ISSUE TITLE
In edited code snippets, "Comparision" should be "Comparison"

### ISSUE THREAD

**Issue by pauamma** [bartTC/dpaste#145]
See https://github.com/bartTC/dpaste/blob/master/dpaste/templates/dpaste/details.html#L85 for the relevant source code line.

Steps to reproduce

1. Create a snippet
2. Edit the snippet
3. Look at the resulting page

Expected result: the first line should read "Comparison with previous snippet"

Actual result: the first line reads "Comparision with previous snippet" (note the added "i")

**Comment by bartTC** [comment]
Thank you!
