### ISSUE TITLE
Problem api

### ISSUE THREAD

**Issue by sor88** [bartTC/dpaste#151]
## Reason for task
There was a problem using the api. After installation, when requesting api, requests with 404 code are returned. Installation went according to the documentation

**Comment by sor88** [comment]
You have incorrectly stated in the instructions or incorrectly indicated in the code the location of the api! if you do everything according to the instructions, then the api will be available at the link * .ru/api/api for it to work correctly, you either need to specify path ('', include ('dpaste.urls.dpaste_api')) in urlspatterns,
    path ('', include ('dpaste.urls.dpaste')),
or edit in the dpaste / urls / dpaste_api.py code replace r "^ api / $" in line 8 with r "^ / $",
Then the instructions can not be edited

**Comment by Nakilon** [comment]
🙄
