### ISSUE TITLE
D language support

### ISSUE THREAD

**Issue by RUSshy** [bartTC/dpaste#154]
## Description
Add D language support

## Acceptance Criteria

- Being able to select D in the select box
- Having syntax highlighting

## Note

I noticed it is commented, what's the reason?

https://github.com/bartTC/dpaste/blob/735f25cc04ef07b4b7d50b60a4d11cbd421d443b/dpaste/apps.py#L271

Thanks!

**Comment by bartTC** [comment]
This is live!

**Comment by RUSshy** [comment]
@bartTC thanks a lot!
