### ISSUE TITLE
Generify the "about" page

### ISSUE THREAD

**Issue by phrawzty** [bartTC/dpaste#42]
The wording of the [about](https://github.com/bartTC/dpaste/blob/master/dpaste/templates/dpaste/about.html) page is specific to the particular [dpaste.de](https://dpaste.de) implementation of this project.  Would it be interesting to make this page more generic so that it fits in any implementation?  If so, I'd be more than happy to write the text for that.

Just a thought - no worries either way. :smile:

**Comment by mk-pmb** [comment]
> removal of Bootstrap
:+1:

**Comment by jloh** [comment]
Whats the reasoning behind wanting to remove bootstrap out of curiosity?

**Comment by bartTC** [comment]
Sure, couple of, nothing is major though:

- dpaste is intended to be integrated into existing projects and I think it shouldn't require or dictate any third party UI styles, class names etc.
- We only use so little of it that the overhead isn't worth it. 100kb CSS just to place an icon and a grid system is reasonable.
- I want to get rid of more third party requirements, and beside Bootstrap also jQuery. We only use it for very little features, and they can be simply done by vanilla JS.
- It looks very dated.

**Comment by bartTC** [comment]
This was done in the v3 branch. Its very barebone in general now.
