### ISSUE TITLE
Add markup formatted output for lexers (Markdown, RSt, Textile, etc.)

### ISSUE THREAD

**Issue by longgeek** [bartTC/dpaste#69]
hi, all.

dpaste.de great, I really like, is now ready to be used in our production environment, to share our subtle results.

The question is, find all the sites are not markdown paste function, it seems that this is a very personal thing painful.
So I want to try type in dpaste.de Canada markdown, I wonder if you can?

**Comment by bartTC** [comment]
What do you think of Markdown here. Have Markdown tags highlighted (like RestructredText Syntax) or really render it to HTML?

**Comment by bartTC** [comment]
There is already the general "Text" lexer (very top) which comes close, it does not parse `[markdown](specific syntax)`

**Comment by longgeek** [comment]
Yes, I want to do is use the highlight syntax highlighted text in specific markdown.

**Comment by longgeek** [comment]
Text does not always seem so beautiful.
https://dpaste.de/pQpH

**Comment by longgeek** [comment]
Should look like this.

![image](https://cloud.githubusercontent.com/assets/2102615/5704679/af97f53e-9aae-11e4-9ab4-5cb469edcd7c.png)

**Comment by bartTC** [comment]
I understand. I have thoughts around this since a while, it probably goes into the 2.0 release (not to be expected earlier Feb).

**Comment by longgeek** [comment]
So Cool～

**Comment by bartTC** [comment]
Ongoing work on this is done in the `markup` branch https://github.com/bartTC/dpaste/tree/markup

**Comment by bartTC** [comment]
This is in and live, for Markdown and rST.
