### ISSUE TITLE
Remove or update (deprecated) django-dpaste PyPI entry

### ISSUE THREAD

**Issue by koobs** [bartTC/dpaste#71]
The [django-dpaste PyPI](https://pypi.python.org/pypi/django-dpaste/) entry currently refers incorrectly to:

 * Its previous (old) name (django-dpaste)
 * An older, deprecated version (0.2.4)
 * An incorrect [github repository URL](http://github.com/bartTC/django-paste/)

Update the entry to redirect it to PyPi: dpaste, or remove the entry, if possible

**Comment by bartTC** [comment]
Thank you, I don't want to remove it just in case somebody really still uses it,but I added a warning and removed the broken links.
