### ISSUE TITLE
why there is no lexer for c++

### ISSUE THREAD

**Issue by introom** [bartTC/dpaste#73]
why there is no lexer for c++

**Comment by bartTC** [comment]
Because nobody asked to implement it.

**Comment by mzmcbride** [comment]
Hi @bartTC.

Can you please re-open this issue? While the tone used here may be a bit off-putting (perhaps by accident!), the substantive issue seems valid. Looking at <https://github.com/bartTC/dpaste/blob/570daee6/dpaste/highlight.py>, it seems language names containing `-` and `+` are currently intentionally excluded? Could we please re-visit that decision? It seems kind of strange to me to hobble `pygment` in this way, when according to <http://pygments.org/languages/> the library supports both C and C++.

If you'd prefer that a new issue be filed instead, I'm happy to do that. Thanks again for this great pastebin! I really like <https://dpaste.de>.

**Comment by mzmcbride** [comment]
Sweet, thank you, @bartTC!
