### ISSUE TITLE
Display The Short URL Code on UI After Pasting

### ISSUE THREAD

**Issue by drveresh** [bartTC/dpaste#84]
Hi,

Can you please update the UI page to display from "Snippet #392350" to "Snippet #392350 - <https://dpaste.de/W82w>"? In addition, a small button/link to copy that link to Clipboard.

I am not sure how that Snippet no# is really helping by displaying as the users would only care and refer its short URL that gets updated only in browser address bar.  It also helps for the following use cases:

1. The Short URL will be on UI page and supports many web development aspects
2. Users can copy and use it from the web page, not just only from address bar
3. Mobile devices, it definitely helps displaying on UI page, because address bar will be very small and have many variations in numerous mobile models
4. Few other benefits can be added by community users

Please let me know if any comments.

- Thanks

**Comment by bartTC** [comment]
Thats a great idea. It's in.

**Comment by mzmcbride** [comment]
Just for reference, fixed with 335fa38.
