### ISSUE TITLE
dpaste performance slows when >60k snippets are in the DB

### ISSUE THREAD

**Issue by ferringb** [bartTC/dpaste#85]
In my setup, I've got over 60k snippets in the DB, and dpaste's speed goes from a previous 'fast' to a few  seconds for new insertion.

Do not run the following code on a live dpaste instance; stand up a test one, it wipes records to control the test.  The following if pasted into a ```django-admin shell``` instance should replicate it- pardon if it's postgres specific:

```
from dpaste.models import Snippet
from django.db import connection
import time
start = time.time()
_ = Snippet(content="asdf").save()
print "empty insert took %2.2f" % (time.time() - start,)

# bulk load; note that Snippet.objects.bulk_create fails w/ a lft exception, likely a bug in mptt.
# hence this approach.
with connection.cursor() as cursor:
  # Wipe the previous record since we have assumptions about secret_id below
  cursor.execute("delete from dpaste_snippet");
  cursor.executemany("""
insert into dpaste_snippet(secret_id, content, lexer, published, expire_type, view_count, lft, rght, tree_id, level)
            values(%s, 'my-content', 'text', CURRENT_TIMESTAMP, 0, 1, 1, 1,
                (SELECT coalesce(max(tree_id), 1) +1 from dpaste_snippet), 0);
  """, [(x,) for x in xrange(60000)])

# Now we time the API call now that we have 60k in there.
from dpaste.models import Snippet
import time
start = time.time()
_ = Snippet(content="asdf").save()
print "took %2.2fs" % (time.time() - start,)
print "finished"
```

In some basic playing in django-admin, I've found that if I disable mptt updates, then performance is normal- I'm still investigating however.

**Comment by ferringb** [comment]
Pardon, forgot to state my timings; empty DB is roughly 0.02s (which is great), with 60k records in the DB however it's ~2s on average for me.

**Comment by bartTC** [comment]
Interesting. I've never stumbled over this problem because the snippets on dpaste.de don't have an infinite life time, I think at max there were about 5k in the db. dpaste.de is using Postgres as well. 

Without further testing I think your benchmarks make sense. dpaste is using Nested Sets which are read-optimized, not for writing. Inserting an item in a Nested set tree requires the entire tree to be rebuild. Your observation on removing mptt makes therefor sense. 

I don't think we can do much there shortnterm, however I do think that I could simply ditch mptt as a requirement and use a simpler, more low level approach to display a tree relation of snippets. They are rarely used so I dont mind it.

**Comment by ferringb** [comment]
What are you thoughts on making the reply/tree functionality optional?  It would require a restructuring of the DB, but it would also make it easy to just plain turn off the feature if desired.

Meanwhile, I'm checking into some hacks that could be leveled in dpaste.models.Snippet.save, specifically setting the tree_id (and lft/rght values) ourselves if  we know we're not replying to a previous paste.  I'll post a PR if that pans out.

**Comment by ferringb** [comment]
Assuming you're happy with the PR I created to work around this, any chance I could get a point release shortly after?  It saves me some work on my end ;)

**Comment by bartTC** [comment]
@ferringb I'd like to do a more drastic approach here and so I removed the entire mptt feature in ae27acf1f9f811088c96664faa398315b5eca96d.

I believe this feature was rarely used after all, the workflow was more over: You reply to a snippet. You want to see show demo the diff between your reply, and the original snippet. You don't want to see a diff between multiple variations of a snippet.  So I removed mptt, but kept the 'answer' and 'snippet parent' relation alive. The interface is more streamlined now. 

I've pushed an alpha release with these changes. You can install it by:

```
pip install dpaste --pre
.. or
pip install dpaste==2.13a
```

I also put it on dpaste.de to test it under live conditions there and gather some feedback.

**Comment by bartTC** [comment]
Please test this on your end too, and reopen the issue if you see any related performance issues.

**Comment by ferringb** [comment]
Well, that too works.  An initial round of testing, this looks perfect- performance is stable.  Thank you-
