### ISSUE TITLE
RAW output line endings

### ISSUE THREAD

**Issue by mathieu-aubin** [bartTC/dpaste#90]
For compatibility, i suggest changing the line endings of the /raw url output to LF (unix style) instead of the currently used CRLF (windows) thus allowing to run pasted snippets in raw format directly from the raw url using something like (for bash scripts example)

```
bash <(curl -sS https://dpaste.de/XXX/raw)
```

**Comment by bartTC** [comment]
Hrm, not sure this is an actual problem dpaste needs to solve. Some thoughts:

1) the CR chracter is not created by dpaste, its coming from the Textarea, its default browser behavior.
2) Using dpaste as a source for scripts does not seem reasonable to me. You have an expire lifetime, why would you rely on a script source, that will expire and get purged?
3) Because of 3, you will likely move to another 'script source' where you face the same problem

I suggest you solve this problem on your side. `tr` or `dos2unix` and most likely `sed` will help you.  `dos2unix` is the simplest way, just pipe your file through it:

```
 ~ $ curl -s https://dpaste.de/ORTr/raw > text.txt
 ~ $ file text.txt
text.txt: ASCII text, with CRLF, LF line terminators

 ~ $ curl -s https://dpaste.de/ORTr/raw | dos2unix > text.txt
 ~ $ file text.txt
text.txt: ASCII text
```

**Comment by mathieu-aubin** [comment]
Yes, thanks for that. 

I guess i should have mentionned i am a linux systems administrator or explained a little more..
dos2unix, yes.. sed is what i generally use. I also rarely paste from a browser but rather straight from a terminal, using the api, and never on any system that remotely ressembles windows.

I have to say i disagree with the 'unreasonable' part of running (whatever it is -- even just getting some text as a variable) straight from any pastebin for a simple reason

Pastebins have for goal to quickly share/demo file contents with the added convenience of a user interface and a bit of code highlight... Running straight from raw files saves a whole lot of time when testing things/quickly demo a function's behavior to a peer and adds that sweetness of not having to explain your client the steps they need to take in order to actually get results from that overly awesome new commoditty your team added to a function.

It adds that second layer to community editing by first reducing actions taken to go from using an online service (ie a pastebin) to output (in the case of a script, a sql query,a complex api call you are explaining someone) a realistic and true to life output as it was meant when first copying data and pasting it.

1000% agreed on the time-limit... In that case where a permanent delivery system would be needed, a permanent delivery system would be used. One that has for purpose/provides such functionnalities as long-term, stable & steady online delivery. Not a pastebin.

Based on my daily routine and how i see pastebins sevices being used amongst my peers,friends and clients, users taking advantage of such service should have less than zero doubts that the output content will be the exact same as what was originally posted, worldwide and on any machine, using such function as a 'view RAW '

To me, the definition of 'raw' does not apply to what is currently being output from the /raw url, thus making its use (at least as it stands now), a little more like a theme, an *"as previously seen on screen"* version of the original data. A ppretty picture of "it" rather then "IT" as the actual thing. In this situation and very unfortunelly, 'RAW' url becomes misleading and a more than evident source of potential conflicts and communication problems between users.

Original data sent, received, handled/tampered-with and stored in the eventual goeal of being displayed as a representation of such data, doesn't really have alot to show for in terms of sparking interrest and user enthousiasm. (altho i am enthousiatic myself and am only stating facts as i see them)

I must say i somehow expected a positive comeback to my suggestion...

**Comment by mathieu-aubin** [comment]
Thanks for replying.
I deleted the last comment as it could have been taken in a bad/the wrong way and that has never been my goal.
another suggestion...
server_tokens off;

**Comment by bartTC** [comment]
I have not seen your previous comment and I don't understand what you mean with above comment. "Server tokens off"?

**Comment by mathieu-aubin** [comment]
In you nginx config,
server_tokens off;
will prevent your nginx version from being displayed.
