### ISSUE TITLE
URL params doesn't seem to work

### ISSUE THREAD

**Issue by Aidenir** [bartTC/dpaste#92]
Trying to change the output format using the format url param, but can't get it to work, only default formatting is returned
curl -v   -F  'content=hj' "https://dpaste.de/api/?format=json"
curl -v   -F  'content=hj' "https://dpaste.de/api/?format=url"
both result in the same output.

**Comment by bartTC** [comment]
Parameters need to be passed via POST 

```
$ curl -v -F 'content=hj' -F 'format=json' https://dpaste.de/api/
{"url": "https://dpaste.de/jS2a", "content": "hj", "lexer": "python"}
```

**Comment by Aidenir** [comment]
Ok I see now the docs says "Available POST data", however the last section on the same page instructs you to alias it as
$ alias dpaste="curl -F 'content=<-' https://dpaste.de/api/?format=url"
http://dpaste.readthedocs.io/en/latest/api.html
