### ISSUE TITLE
Choose syntax highlight on reading

### ISSUE THREAD

**Issue by weichuliu** [bartTC/dpaste#93]
After saving a snippet with a certain syntax, it seems not possible to change the highlight unless you create a new snippet with the other syntax.

The syntax detection and selection should be done on reading, so that it will be much flexible to see the snippet in any highlight.

**Comment by bartTC** [comment]
@weichuliu I think thats generally a good idea but I can't remember really needing this. Snippets are not permanently stored, so I don't it proves enough value to introduce another UI element. I like to keep the interface as simple as possible.
