### ISSUE TITLE
About CSRF Token

### ISSUE THREAD

**Issue by mathieu-aubin** [bartTC/dpaste#94]
Hi, 

Using the typical 'curl' method mentionned in the documentation results in a CSRF token problem for which i have problems finding a solution to. I was wondering to what extent is csrf verification needed from such a service or, is it maybe simply a mistake having re-enabled it after an app upgrade/change?

Html outputs a 403 with this (extra line on top too it seems)

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <meta name="robots" content="NONE,NOARCHIVE">
  <title>403 Forbidden</title>
  <style type="text/css">
    html * { padding:0; margin:0; }
    body * { padding:10px 20px; }
    body * * { padding:0; }
    body { font:small sans-serif; background:#eee; }
    body>div { border-bottom:1px solid #ddd; }
    h1 { font-weight:normal; margin-bottom:.4em; }
    h1 span { font-size:60%; color:#666; font-weight:normal; }
    #info { background:#f6f6f6; }
    #info ul { margin: 0.5em 4em; }
    #info p, #summary p { padding-top:10px; }
    #summary { background: #ffc; }
    #explanation { background:#eee; border-bottom: 0px none; }
  </style>
</head>
<body>
<div id="summary">
  <h1>Forbidden <span>(403)</span></h1>
  <p>CSRF verification failed. Request aborted.</p>


</div>

<div id="explanation">
  <p><small>More information is available with DEBUG=True.</small></p>
</div>

</body>
</html>
```

on a typical day, i probably use the service at least 5 times from a custom app i created for myself on many different servers... it would be neat to keep using the service without ultimately having the app running privately.

Thanks for the good work!

**Comment by bartTC** [comment]
No, this is certainly a bug, the API should not have any sort of CSRF protection (it makes no sense, since no cookies). I put the `v3` beta branch on dpaste.de for testing that introduced it. 

Will be fixed asap.

**Comment by bartTC** [comment]
Fixed and tested. Thank you for the report.

**Comment by mathieu-aubin** [comment]
Pleasure.
